trigger: none
pr: none

schedules:
  - cron: "30 5 * * *" # Time is UTC
    displayName: Nightly Code Coverage Build
    branches:
      include:
        - master
    always: true

jobs:
- job: Linux
  pool:
    vmImage: 'ubuntu-latest'
  steps:
  - script: echo hello from Linux
- job: macOS
  pool:
    vmImage: 'macOS-latest'
  steps:
  - script: echo hello from macOS
- job: Windows
  pool:
    vmImage: 'windows-latest'
  steps:
  - script: echo hello from Windows

  matrix:
    python35:
      imageName: '3.5'
    python36:
      imageName: '3.6'
  - template: nightly_template.yml

steps:
  - script: python -m pip install --upgrade pip
    displayName: 'Install tools'

  - bash: |
      pip install --upgrade pip
    displayName: Upgrade pip to latest

  - bash: |
      pip install -r requirements.txt
    displayName: Install required pip packages

  - bash: |
      pip install -e ./python
    displayName: Install interpret-extensions

  - bash: |
      pip install --upgrade setuptools wheel twine
      cd ./python
      python setup.py bdist_wheel
      cd ..
    displayName: Create a wheel

  - task: TwineAuthenticate@0
    displayName: Configure twine authentication
    inputs:
      artifactFeeds: $(artifactFeed)

  - bash: |
      cd ./python
      twine upload -r $(artifactFeed) --config-file $(PYPIRC_PATH) dist/*
      cd ..
    displayName: Publish artifacts

  - bash: |
      flake8 --max-line-length=119 --exclude=.git/,__pycache__/,dist/ .
    displayName: "Run flake8"

  - bash: |
      python -m pytest test/ --junitxml=./TEST-TEST.xml
    displayName: "Run tests"

  - task: PublishTestResults@2
    displayName: "Publish Test Results **/TEST-*.xml"
    condition: succeededOrFailed()
